### ISSUE TITLE
UWP Xamarin Forms application with Caliburn.Micro version 4.0.135-beta

### ISSUE THREAD

**Issue by schovan** [Caliburn-Micro/Caliburn.Micro#707]
Hello,
I would like to ask:
- Where can I find the source code for the package Caliburn.Micro.Xamarin.Forms?
or
- I need a package Caliburn.Micro.Xamarin.Forms referencing package Caliburn.Micro.Core version 4.0.135-beta(because I have a version conflict). How do I solve this?

Edit: My scenario - one assembly uses Caliburn.Micro.Xamarin.Forms UWP, one assembly uses Caliburn.Micro WPF .Net Core, one shared assembly uses Caliburn.Micro.Core)

**Comment by nigel-sampson** [comment]
In the 4.x versions I've collapsed the Caliburn.Micro.Xamarin.Forms package back into the Caliburn.Micro package.

**Comment by schovan** [comment]
I'm not sure, if I understand you correctly. Do you mean that package Caliburn.Micro.Xamarin.Forms is included in package Caliburn.Micro version 4.0.135-alpha? Because I cannot find there for example class Caliburn.Micro.Xamarin.Forms.FormsApplication

**Comment by nigel-sampson** [comment]
You can see it at https://github.com/Caliburn-Micro/Caliburn.Micro/blob/master/src/Caliburn.Micro.Platform/Platforms/Xamarin.Forms/FormsApplication.cs

**Comment by schovan** [comment]
Thank you, now I can find it. But unfortunatelly, my project is still not buildable. I have an UWP application that uses Xamarin Forms and Caliburn Micro. It works with previous implementation with standalone Caliburn.Micro.Xamarin.Forms version 4.0.0-alpha1. Now in Caliburn.Micro version 4.0.135-beta, it looks like that needed classes are in netstandard2.0\Caliburn.Micro.Platform.dll and uap10.0.16299\Caliburn.Micro.Platform.dll, but both cannot be loaded. I'm getting an error at this line
```
LoadApplication(new FormsApp(IoC.Get<SimpleContainer>()));
```
and the errors are:
```
error CS7069: Reference to type 'FormsApplication' claims it is defined in 'Caliburn.Micro.Platform', but it could not be found
error CS1503: Argument 1: cannot convert from 'CardGame.UWP.FormsApp' to 'Xamarin.Forms.Application'
```
Do you know some trick, how to make it working?

**Comment by nigel-sampson** [comment]
Ok, now I get you, let me look into it.

**Comment by nigel-sampson** [comment]
I don't think we're supporting Xamarin.Forms UWP with the project system. Right now its using the platform type like uwp / netstandard to work out which "flavour" of CM to use.  In your case its assuming you want UWP, but what you want is XF on UWP.

Having XF solved this, but created long term problems in maintaining the package.

**Comment by schovan** [comment]
I do not understand. Previsously, it was working in 4.0.0-alpha1 version with the special package Caliburn.Micro.Xamarin.Forms. Combinations UWP + Xamarin Forms, Android + Xamarin Forms, iOS + Xamarin Forms was working. Now in version 4.0.135-beta, no combination is working. How can Xamarin Forms work in version 4.0.135-beta? Do you have some examples? What is the of purpose of Caliburn.Micro.Platform.dll type Xamarin.Forms? What can it do without a second platform? Maybe I cannot see it, but it looks useless to me.

**Comment by nigel-sampson** [comment]
The new build system doesn't allow dependent assemblies to be added to the automatically created packages. Previously I had a `Caliburn.Micro.Platform.Core` assembly that contained a lot of shared code between the `Platform` and `Platform.Xamarin.Forms` assemblies that shouldn't be its own package but it couldn't get bundled into that `Platform` package.

This meant maintaining the `Xamarin.Forms` package separately wasn't going to work.  The UWP with Xamarin.Forms scenario you hit was the unintended conseuquence.

**Comment by KasperSK** [comment]
I think we could close this issue as it was fixed by #726.
